### ISSUE TITLE
`terminedia-plot` wrong axis position and selection

### ISSUE THREAD

**Issue by vytas7** [jsbueno/terminedia#28]
It seems that `terminedia-plot` plots points at a wrong _y_ coordinate.

For instance, `terminedia-plot --func x` yields:
![image](https://user-images.githubusercontent.com/3430939/140605399-23347315-1c50-4286-8278-8b8f02859ce2.png)
From the graph, I'm getting an impression that _f_(0.01) ≈ 2, which is obviously not even remotely true for _f_(_x_) = _x_.

(One can also see a minor cosmetic issue, a data point seems to be missing on the graph.)

`terminedia-plot --func x*x` seems to provide a roughly correct data point for (0, 0), but the choice for _y_ range seems to be quite odd:
![image](https://user-images.githubusercontent.com/3430939/140605443-668422ef-530b-4f84-8d6a-a114982411a2.png)

**Comment by vytas7** [comment]
Hi, this is still a problem :slightly_smiling_face: (Not a _problem_ in the sense I'm using `terminedia` for anything but fun, but still).

`f(x) = x` now works as expected.
`f(x) = x*x` is now wrong instead, it looks like f(0) = -4 or smth for x*x.

**Comment by jsbueno** [comment]
Fixed by commit  be4b0324

Turns out I've evolved this form a very simple script in the early days of the project - and I was inverting the y value to be plotted right were it is calculated - instead of keeping a sane internal y value for the points and just reversing in the right direction at plot time.
